[package]
name = "survive-the-course-rs"
version = "0.1.0"
authors = ["Yukio Usuzumi <anohigisavay@gmail.com>"]
edition = "2021"

[dependencies]
test-util = { path = "test-util" }

[workspace]
members = ["test-util"]
